feat: support wildcard filetypes for null-ls providers
ChristianChiarulli/nvcode pull request #1447
Opened 2021-09-01 18:24 UTC by Tastyep

# Description

Some builtins from null-ls have '*' for file type, this is now supported on our side as well.
I also added some utility functions for tables, `any_of` and `find_if` and replaced parts of the code to use them.
Some key-mappings for compe were hardcoded, I moved them to the configuration and added support for `select_mode` key-mappings.

Convert - to _ when resolving builtins command to name.

Fixes #1196 

## How Has This Been Tested?

`:LvimInfo` will now show spelling linters.
I checked that tab and stab were still working in the completion menu.
Configure cmake-format and open a CMakeLists.txt file

2021-09-01 19:12 UTC, abzcoding commented
i get this error while using it, not sure why 
<img width="1067" alt="Screen Shot 2021-09-01 at 11 39 08 PM" src="https://user-images.githubusercontent.com/10992695/131730008-69f67792-bd39-4d97-8086-f6eeb5dc2dc0.png">

2021-09-01 19:13 UTC, abzcoding commented on lua/core/compe.lua
> +          ["<Tab>"] = { "v:lua.tab_complete()" },
maybe because this line and the one below it

2021-09-02 08:24 UTC, abzcoding approved these changes

2021-09-04 11:30 UTC, kylo252 requested changes
You can use `vim.tbl_filter` for this. That way we can avoid defining what appears to be a new "type" of table 😅

2021-09-04 11:54 UTC, Tastyep commented
> You can use `vim.tbl_filter` for this. That way we can avoid defining what appears to be a new "type" of table sweat_smile

But I don't want a filtered table, I want to find the matching element

2021-09-04 12:06 UTC, kylo252 commented
> > You can use `vim.tbl_filter` for this. That way we can avoid defining what appears to be a new "type" of table sweat_smile
> 
> But I don't want a filtered table, I want to find the matching element

How are these two not the same? 

There's also `vim.tbl_map` if you need something a little bit different.

2021-09-04 12:24 UTC, Tastyep commented
> > > You can use `vim.tbl_filter` for this. That way we can avoid defining what appears to be a new "type" of table sweat_smile
> > 
> > 
> > But I don't want a filtered table, I want to find the matching element
> 
> How are these two not the same?
> 
> There's also `vim.tbl_map` if you need something a little bit different.

One returns a table, the other one returns the entry. `tbl_map` doesn't do what I want either.

2021-09-04 13:50 UTC, kylo252 commented
> One returns a table, the other one returns the entry. `tbl_map` doesn't do what I want either.

You can just take the first element of the filtered table and discard the rest if you want. what am I missing here?

I believe this should do it

```lua
function M.get_active_client_by_ft(filetype)
  if not lvim.lang[filetype] or not lvim.lang[filetype].lsp then
    return nil
  end

  local clients = vim.lsp.get_active_clients()
  return vim.tbl_filter(function(client)
    return client.name == lvim.lang[filetype].lsp.provider
  end, clients)
end
```

I even have a FIXME on that function because it's only picking up the first client :(

2021-09-04 15:09 UTC, Tastyep commented
> > One returns a table, the other one returns the entry. `tbl_map` doesn't do what I want either.
> 
> You can just take the first element of the filtered table and discard the rest if you want. what am I missing here?
> 
> I believe this should do it
> 
> ```lua
> function M.get_active_client_by_ft(filetype)
>   if not lvim.lang[filetype] or not lvim.lang[filetype].lsp then
>     return nil
>   end
> 
>   local clients = vim.lsp.get_active_clients()
>   return vim.tbl_filter(function(client)
>     return client.name == lvim.lang[filetype].lsp.provider
>   end, clients)
> end
> ```
> 
> I even have a FIXME on that function because it's only picking up the first client :(

Feel free to make a PR to support returning a list once you've merged your other PRs

2021-09-05 13:20 UTC, kylo252 commented
> > I even have a FIXME on that function because it's only picking up the first client :(
> 
> Feel free to make a PR to support returning a list once you've merged your other PRs

As I said, you can just take first value and ignore the rest if you want one value. If you want to see if the predicate worked then you just see if there are elements in the return value. It really doesn't make sense to add a function with a slightly different name that does the same exact thing. 

> _In functional programming, filter is a higher-order function that processes a data structure (usually a list) in some order to produce a new data structure containing exactly those elements of the original data structure for which a given predicate returns the boolean value true._

You can create a lambda, call it `if_any` and pass it to `vim.tbl_filter`. Now you have the big advantage that people already know how the library function work, so when there's something broken. It's one less thing to think about. How often are we even going to use that?

2021-09-05 13:42 UTC, Tastyep commented
Sorry, but I don't agree with your suggestions.
``` lua
  local client = tbl.find_if(clients, function(client)
    return client.name == lvim.lang[filetype].lsp.provider
  end)
```

``` lua
  local client = vim.tbl_filter(function(client)
    return client.name == lvim.lang[filetype].lsp.provider
  end, clients)[1]
```

Note that additionally to better semantic, my function doesn't need to iterate over the whole array in case the element is found, neither does it need to create a new table.

> how the library function work

Is a  well named, documented, < 10lines function is too hard to understand, really ?
I come from a c++ background, so to me these functions are standard, but still.

> So when there's something broken

Luckily, we will be able to implement tests in a near future.

Really, I don't understand your reason for preferring accommodating tbl_filter to match your usage instead of having a well-defined function that does one job and is explicit about it.
It seems to me that you are against adding new code more than against this function, maybe I'm wrong.

2021-09-05 17:04 UTC, kylo252 commented
I feel like you missed the most important point "_How often are we even going to use that?_"

> Note that additionally to better semantic, my function doesn't need to iterate over the whole array in case the element is found, neither does it need to create a new table.

How many filetypes are there? what's the longest possible list of filetypes where you think this optimization is gonna matter, or is this future-proofing?

> Luckily, we will be able to implement tests in a near future.

Testing and rationalizing about a specialized function is easier every day of the week. And we don't need to test library calls.

> Is a well named, documented, < 10lines function too hard to understand, really ?
> I come from a c++ background, so to me these functions are standard, but still I would have expected that to be easy to understand, I even matched the variable names `Table` -> `tbl`.

It's about avoiding unnecessary complexity. I've learned to always try to use well validated and tested library calls unless I have a very good reason not to. And so far I see zero evidence how these offer any benefits. And again, one of them is literally used in a buggy function anyway.

> Really, I don't understand your reason for preferring accommodating tbl_filter to match your usage instead of having a well-defined function that does one job and is explicit about it.
> It seems to me that you are against adding new code more than against this function, maybe I'm wrong.

I think it's fair to say we're not writing a library.


Since I already gave an example for `get_active_clients_by_ft()`, let me suggest this for the other use-case: 


```lua
  function M.list_available(filetype)
    local linters = {}
    local tbl = require "utils.table"
    for _, provider in pairs(null_ls.builtins.diagnostics) do
      if vim.tbl_contains(provider.filetypes or {}, ft) then
        table.insert(linters, provider.name)
      end
    end
    return linters
  end
```

I'm not really sure you can give any argument against it compared to what you have here:

```lua
function M.list_available(filetype)
  local linters = {}
  local tbl = require "utils.table"
  for _, provider in pairs(null_ls.builtins.diagnostics) do
    if tbl.any_of(provider.filetypes or {}, function(ft)
      return ft == "*" or ft == filetype
    end) then
      table.insert(linters, provider.name)
    end
  end
  return linters
end

```

2021-09-06 08:41 UTC, Tastyep commented
>I'm not really sure you can give any argument against it compared to what you have here

Only that it doesn't support wildcards, which was the goal of the PR.
I'm not answering anymore, feel free to merge or delete the PR.

2021-09-06 16:15 UTC, kylo252 commented
Let's leave the tie-breaker to @rebuilt 😃

2021-09-07 16:55 UTC, rebuilt commented
As the dumbest person in the room, I'm glad you left it to me to decide.  My abilities better match those of the average person reading this code.   😅 

@Tasty I think the functions you wrote need better names so anyone reading the code can better infer the arguments and return values.  The functions you wrote are short and well written but they will never be as easy to understand as functions coders already know.  

When I read `local client = vim.tbl_filter`, I instantly know what arguments this function is supposed to take and what will likely be returned.  I do not have to read the source code to understand what it does. 

When I read 'local client = tbl.find_if`, I can make NO assumptions about the arguments the function takes or what it returns.  I am forced to go to the definition and read what it does.  

`tbl.find_if` acts a lot like `tbl.find_first`.  I'm not sure if this name is clearer or not.  Can we come up with a better name?  I'd rather have a longer name that describes the intent than a short but vague name.

I wasn't quite sure what `any_of` should return.  Once I read the source I mentally changed the name to `contains_any_of` which made the return of boolean seem more obvious.

2021-10-09 08:54 UTC, abzcoding commented
btw in the new workflow, we don't need this, we can just use the normal null-ls
for example instead of setting prettierd 10 times, we can just use
<img width="698" alt="Screen Shot 2021-10-09 at 12 23 46 PM" src="https://user-images.githubusercontent.com/10992695/136651579-e7485ac1-d01a-449e-b90e-fde24e8dd3e0.png">

2021-10-09 09:08 UTC, kylo252 commented
> btw in the new workflow, we don't need this

Yes and no, this is solving a few different issues at once. I've been able to verify at least one of them, this actually works now:

```lua
lvim.lang.markdown.linters = { { exe = "write-good" } }
```
The other issue it solves is providers that will return `{'*'}` as their filetype, but this PR is done before I had refactored null-ls. I'm not sure this will break anything because we've since been using a null-ls utility:
https://github.com/LunarVim/LunarVim/blob/5fef931d8720f2ef0d7a0fca18b96f31fd36689a/lua/lsp/null-ls/services.lua#L53-L55

> we can just use the normal null-ls for example instead of setting prettierd 10 times

I can already do this with our API. Just need to add like 2 lines of code, so I'm gonna fix it quickly.

2021-10-09 11:45 UTC, merged